create table public.market_data_categories (
  code text primary key
    check (code ~ '^[a-z][a-z0-9_]{1,49}$'),
  description text not null
    check (char_length(trim(description)) between 10 and 500),
  created_at timestamptz not null default now()
);

insert into public.market_data_categories (code, description)
values
  ('official_statistics', 'Published statistics from a government or intergovernmental institution.'),
  ('commodity_price', 'Measured commodity or input-price series from an identified data provider.'),
  ('exchange_rate', 'Published currency exchange-rate series from an identified data provider.'),
  ('company_disclosure', 'First-party company filing, disclosure, or investor-relations publication.'),
  ('market_news', 'Publisher-attributed market reporting retained as a source document, not a measured fact.'),
  ('search_interest', 'Relative search-interest measurement; it is not sales volume or absolute demand.')
on conflict (code) do update
set description = excluded.description;

create table public.market_sources (
  id bigint generated by default as identity primary key,
  code text not null unique
    check (code ~ '^[a-z][a-z0-9_]{1,49}$'),
  name text not null
    check (char_length(trim(name)) between 2 and 120),
  homepage_url text not null
    check (homepage_url ~ '^https://' and char_length(homepage_url) <= 2048),
  documentation_url text
    check (
      documentation_url is null
      or documentation_url ~ '^https://' and char_length(documentation_url) <= 2048
    ),
  terms_url text
    check (terms_url is null or terms_url ~ '^https://' and char_length(terms_url) <= 2048),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.market_source_categories (
  market_source_id bigint not null references public.market_sources(id)
    on delete restrict,
  category_code text not null references public.market_data_categories(code)
    on delete restrict,
  created_at timestamptz not null default now(),
  primary key (market_source_id, category_code)
);

insert into public.market_sources (
  code,
  name,
  homepage_url,
  documentation_url,
  terms_url
)
values
  (
    'bps',
    'Badan Pusat Statistik',
    'https://www.bps.go.id',
    'https://webapi.bps.go.id/developer',
    'https://webapi.bps.go.id/developer'
  ),
  (
    'world_bank',
    'World Bank',
    'https://data.worldbank.org',
    'https://datahelpdesk.worldbank.org/knowledgebase/topics/125589',
    'https://www.worldbank.org/en/about/legal'
  ),
  (
    'fred',
    'Federal Reserve Economic Data',
    'https://fred.stlouisfed.org',
    'https://fred.stlouisfed.org/docs/api/fred/',
    'https://fred.stlouisfed.org/docs/api/terms_of_use.html'
  ),
  (
    'sec_edgar',
    'SEC EDGAR',
    'https://www.sec.gov/edgar',
    'https://www.sec.gov/search-filings/edgar-application-programming-interfaces',
    'https://www.sec.gov/about/privacy-information'
  ),
  (
    'gdelt',
    'GDELT',
    'https://www.gdeltproject.org',
    'https://docs.gdeltcloud.com/API_DOCUMENTATION_GUIDE',
    null
  ),
  (
    'alpha_vantage',
    'Alpha Vantage',
    'https://www.alphavantage.co',
    'https://www.alphavantage.co/documentation/',
    'https://www.alphavantage.co/terms_of_service/'
  )
on conflict (code) do update
set
  name = excluded.name,
  homepage_url = excluded.homepage_url,
  documentation_url = excluded.documentation_url,
  terms_url = excluded.terms_url;

insert into public.market_source_categories (market_source_id, category_code)
select source.id, mapping.category_code
from (
  values
    ('bps', 'official_statistics'),
    ('world_bank', 'official_statistics'),
    ('fred', 'official_statistics'),
    ('fred', 'commodity_price'),
    ('fred', 'exchange_rate'),
    ('sec_edgar', 'company_disclosure'),
    ('gdelt', 'market_news'),
    ('alpha_vantage', 'commodity_price'),
    ('alpha_vantage', 'exchange_rate')
) as mapping(source_code, category_code)
join public.market_sources source on source.code = mapping.source_code
on conflict do nothing;

create table public.market_product_source_bindings (
  id uuid primary key default extensions.gen_random_uuid(),
  workspace_id uuid not null references public.workspaces(id)
    on delete cascade,
  product_id uuid not null,
  market_source_id bigint not null,
  category_code text not null,
  external_identifier text not null
    check (char_length(trim(external_identifier)) between 1 and 200),
  country_code text references public.countries(code)
    on delete restrict,
  region_code text
    check (region_code is null or char_length(trim(region_code)) between 1 and 50),
  refresh_interval_minutes integer not null default 1440
    check (refresh_interval_minutes between 5 and 43200),
  is_active boolean not null default true,
  created_by uuid not null references public.profiles(user_id)
    on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint market_product_source_bindings_product_fkey
    foreign key (workspace_id, product_id)
    references public.market_products(workspace_id, id)
    on delete cascade,
  constraint market_product_source_bindings_source_category_fkey
    foreign key (market_source_id, category_code)
    references public.market_source_categories(market_source_id, category_code)
    on delete restrict,
  constraint market_product_source_bindings_identity_key
    unique (workspace_id, product_id, id, market_source_id, category_code),
  constraint market_product_source_bindings_external_key
    unique nulls not distinct (
      workspace_id,
      product_id,
      market_source_id,
      category_code,
      external_identifier,
      country_code,
      region_code
    )
);

create table public.market_observations (
  id uuid primary key default extensions.gen_random_uuid(),
  workspace_id uuid not null references public.workspaces(id)
    on delete cascade,
  product_id uuid not null,
  binding_id uuid not null,
  market_source_id bigint not null,
  category_code text not null,
  source_record_id text not null
    check (char_length(trim(source_record_id)) between 1 and 300),
  metric_code text not null
    check (metric_code ~ '^[A-Za-z0-9][A-Za-z0-9._:-]{0,119}$'),
  numeric_value numeric not null
    check (abs(numeric_value) < 1e30),
  unit_code text not null
    check (unit_code ~ '^[A-Za-z0-9][A-Za-z0-9._/%:-]{0,31}$'),
  observed_at timestamptz not null,
  fetched_at timestamptz not null default now(),
  source_url text not null
    check (source_url ~ '^https://' and char_length(source_url) <= 2048),
  raw_payload_sha256 text not null
    check (raw_payload_sha256 ~ '^[0-9a-f]{64}$'),
  created_at timestamptz not null default now(),
  constraint market_observations_binding_fkey
    foreign key (
      workspace_id,
      product_id,
      binding_id,
      market_source_id,
      category_code
    ) references public.market_product_source_bindings(
      workspace_id,
      product_id,
      id,
      market_source_id,
      category_code
    ) on delete cascade,
  constraint market_observations_fetch_order_check
    check (fetched_at >= observed_at),
  constraint market_observations_source_record_key
    unique (binding_id, source_record_id, metric_code, observed_at)
);

create table public.market_source_documents (
  id uuid primary key default extensions.gen_random_uuid(),
  workspace_id uuid not null references public.workspaces(id)
    on delete cascade,
  product_id uuid not null,
  binding_id uuid not null,
  market_source_id bigint not null,
  category_code text not null,
  source_record_id text not null
    check (char_length(trim(source_record_id)) between 1 and 300),
  title text not null
    check (char_length(trim(title)) between 2 and 500),
  canonical_url text not null
    check (canonical_url ~ '^https://' and char_length(canonical_url) <= 2048),
  publisher_name text not null
    check (char_length(trim(publisher_name)) between 2 and 160),
  published_at timestamptz not null,
  fetched_at timestamptz not null default now(),
  language_code text
    check (language_code is null or language_code ~ '^[a-z]{2,3}(-[A-Z]{2})?$'),
  country_code text references public.countries(code)
    on delete restrict,
  raw_payload_sha256 text not null
    check (raw_payload_sha256 ~ '^[0-9a-f]{64}$'),
  created_at timestamptz not null default now(),
  constraint market_source_documents_binding_fkey
    foreign key (
      workspace_id,
      product_id,
      binding_id,
      market_source_id,
      category_code
    ) references public.market_product_source_bindings(
      workspace_id,
      product_id,
      id,
      market_source_id,
      category_code
    ) on delete cascade,
  constraint market_source_documents_fetch_order_check
    check (fetched_at >= published_at),
  constraint market_source_documents_source_record_key
    unique (binding_id, source_record_id)
);

create type public.market_sync_outcome as enum (
  'running',
  'succeeded',
  'failed'
);

create table public.market_source_sync_runs (
  id uuid primary key default extensions.gen_random_uuid(),
  workspace_id uuid not null references public.workspaces(id)
    on delete cascade,
  product_id uuid not null,
  binding_id uuid not null,
  market_source_id bigint not null,
  category_code text not null,
  sync_outcome public.market_sync_outcome not null default 'running',
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  fetched_count integer not null default 0
    check (fetched_count between 0 and 1000000),
  accepted_count integer not null default 0
    check (accepted_count between 0 and fetched_count),
  error_code text
    check (error_code is null or error_code ~ '^[A-Z][A-Z0-9_]{1,79}$'),
  created_at timestamptz not null default now(),
  constraint market_source_sync_runs_binding_fkey
    foreign key (
      workspace_id,
      product_id,
      binding_id,
      market_source_id,
      category_code
    ) references public.market_product_source_bindings(
      workspace_id,
      product_id,
      id,
      market_source_id,
      category_code
    ) on delete cascade,
  constraint market_source_sync_runs_lifecycle_check check (
    (sync_outcome = 'running' and completed_at is null and error_code is null)
    or
    (sync_outcome = 'succeeded' and completed_at is not null and error_code is null)
    or
    (sync_outcome = 'failed' and completed_at is not null and error_code is not null)
  ),
  constraint market_source_sync_runs_time_order_check
    check (completed_at is null or completed_at >= started_at)
);

create index market_product_source_bindings_active_idx
on public.market_product_source_bindings (workspace_id, is_active, product_id);

create index market_observations_product_time_idx
on public.market_observations (workspace_id, product_id, observed_at desc);

create index market_observations_binding_time_idx
on public.market_observations (binding_id, observed_at desc);

create index market_source_documents_product_time_idx
on public.market_source_documents (workspace_id, product_id, published_at desc);

create index market_source_sync_runs_binding_time_idx
on public.market_source_sync_runs (workspace_id, binding_id, started_at desc);

create trigger market_sources_set_updated_at
before update on public.market_sources
for each row execute function private.set_updated_at();

create trigger market_product_source_bindings_set_updated_at
before update on public.market_product_source_bindings
for each row execute function private.set_updated_at();

alter table public.market_data_categories enable row level security;
alter table public.market_sources enable row level security;
alter table public.market_source_categories enable row level security;
alter table public.market_product_source_bindings enable row level security;
alter table public.market_observations enable row level security;
alter table public.market_source_documents enable row level security;
alter table public.market_source_sync_runs enable row level security;

create policy "market_categories_read_authenticated"
on public.market_data_categories for select to authenticated
using (true);

create policy "market_sources_read_authenticated"
on public.market_sources for select to authenticated
using (true);

create policy "market_source_categories_read_authenticated"
on public.market_source_categories for select to authenticated
using (true);

create policy "market_bindings_select_permitted"
on public.market_product_source_bindings for select to authenticated
using (private.has_workspace_permission(workspace_id, 'market.read'));

create policy "market_bindings_insert_permitted"
on public.market_product_source_bindings for insert to authenticated
with check (
  created_by = (select auth.uid())
  and private.has_workspace_permission(workspace_id, 'market.write')
);

create policy "market_bindings_update_permitted"
on public.market_product_source_bindings for update to authenticated
using (private.has_workspace_permission(workspace_id, 'market.write'))
with check (
  private.has_workspace_permission(workspace_id, 'market.write')
);

create policy "market_bindings_delete_permitted"
on public.market_product_source_bindings for delete to authenticated
using (private.has_workspace_permission(workspace_id, 'market.delete'));

create policy "market_observations_select_permitted"
on public.market_observations for select to authenticated
using (private.has_workspace_permission(workspace_id, 'market.read'));

create policy "market_source_documents_select_permitted"
on public.market_source_documents for select to authenticated
using (private.has_workspace_permission(workspace_id, 'market.read'));

create policy "market_source_sync_runs_select_permitted"
on public.market_source_sync_runs for select to authenticated
using (private.has_workspace_permission(workspace_id, 'market.read'));

revoke all on public.market_data_categories from public, anon, authenticated;
revoke all on public.market_sources from public, anon, authenticated;
revoke all on public.market_source_categories from public, anon, authenticated;
revoke all on public.market_product_source_bindings from public, anon, authenticated;
revoke all on public.market_observations from public, anon, authenticated;
revoke all on public.market_source_documents from public, anon, authenticated;
revoke all on public.market_source_sync_runs from public, anon, authenticated;

grant select on public.market_data_categories to authenticated;
grant select on public.market_sources to authenticated;
grant select on public.market_source_categories to authenticated;

grant select on public.market_product_source_bindings to authenticated;
grant insert (
  workspace_id,
  product_id,
  market_source_id,
  category_code,
  external_identifier,
  country_code,
  region_code,
  refresh_interval_minutes,
  is_active,
  created_by
) on public.market_product_source_bindings to authenticated;
grant update (
  external_identifier,
  country_code,
  region_code,
  refresh_interval_minutes,
  is_active
) on public.market_product_source_bindings to authenticated;
grant delete on public.market_product_source_bindings to authenticated;

grant select on public.market_observations to authenticated;
grant select on public.market_source_documents to authenticated;
grant select on public.market_source_sync_runs to authenticated;

grant select on public.market_data_categories to service_role;
grant select on public.market_sources to service_role;
grant select on public.market_source_categories to service_role;
grant select on public.market_product_source_bindings to service_role;
grant select, insert on public.market_observations to service_role;
grant select, insert on public.market_source_documents to service_role;
grant select, insert, update on public.market_source_sync_runs to service_role;

comment on table public.market_data_categories is
  'Controlled factual-market classification; UI translations are application-owned.';
comment on table public.market_sources is
  'Provider registry only; API credentials remain in trusted deployment secrets.';
comment on table public.market_product_source_bindings is
  'Workspace configuration mapping a monitored product to one provider series, query, filing identity, or feed.';
comment on table public.market_observations is
  'Provider-attributed quantitative evidence written only by trusted ingestion; it is not an AI interpretation.';
comment on table public.market_source_documents is
  'Provider-attributed document metadata and canonical URL; article content and AI summaries are not stored here.';
comment on table public.market_source_sync_runs is
  'Bounded synchronization state for freshness and failure display; error codes contain no provider payload or secret.';
comment on table public.market_snapshots is
  'User-recorded market observation, distinct from trusted external market observations.';
